//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class accident
    {
        public int id_accident { get; set; }
        public string description_a { get; set; }
        public System.DateTime date_time_accident { get; set; }
        public int id_address { get; set; }
        public int id_driver { get; set; }
        public int id_car { get; set; }
    
        public virtual address address { get; set; }
        public virtual car car { get; set; }
        public virtual driver driver { get; set; }
    }
}
