//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer
    {
        public int id_employer { get; set; }
        public int id_employer_rank { get; set; }
        public int id_employer_position { get; set; }
    
        public virtual employer_rank employer_rank { get; set; }
        public virtual employer_position employer_position { get; set; }
    }
}
