//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MREO0Entities : DbContext
    {
        public MREO0Entities()
            : base("name=MREO0Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accident> accident { get; set; }
        public virtual DbSet<accounting> accounting { get; set; }
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<body_type> body_type { get; set; }
        public virtual DbSet<building_number> building_number { get; set; }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<car_number> car_number { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<driver> driver { get; set; }
        public virtual DbSet<driver_license> driver_license { get; set; }
        public virtual DbSet<employer> employer { get; set; }
        public virtual DbSet<employer_position> employer_position { get; set; }
        public virtual DbSet<employer_rank> employer_rank { get; set; }
        public virtual DbSet<engine_type> engine_type { get; set; }
        public virtual DbSet<mark> mark { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<ownership_type> ownership_type { get; set; }
        public virtual DbSet<passport> passport { get; set; }
        public virtual DbSet<street> street { get; set; }
    }
}
